tnd_snipcart:
  api_key: MDVhYjZlMmItZTBjMy00ZTRhLWJmZTUtNjFkOGE1MTY4NTFiNjM2NDIyOTkzMzEwMDQyNzA4
  front_matter_key: none
  global:
    modal-style: side
  forms:
    _default:
      buy_button_text: Add to cart
      buy_button_classes: "bg-red bn fw6 h-2_5 hover-b--c-red hover-ba hover-bg-white hover-bw1 hover-c-red jean-luc pointer tracked-narrow w-8_5 white   snipcart-add-item"
    with_sizes:
      buy_button_text: Buy {{price}}$
      fields:
        - id: size
          name: Size