tnd_snipcart:
  api_key: MDVhYjZlMmItZTBjMy00ZTRhLWJmZTUtNjFkOGE1MTY4NTFiNjM2NDIyOTkzMzEwMDQyNzA4
  front_matter_key: none
  global:
    modal-style: side
  forms:
    _default:
      buy_button_text: Add to cart
      buy_button_classes: "bg-bm-magenta bn fw6 h-2_5 hover-bg-pink-ladies hover-ba hover-bw1 jean-luc pointer tracked-narrow w-8_5 white   snipcart-add-item"
    with_sizes:
      buy_button_text: Buy {{price}}$
      fields:
        - id: size
          name: Size