[build]
publish = "public"
command = "hugo --gc --minify"
functions = ".functions"

[build.environment]
HUGO_VERSION = "0.89.1"
GO_VERSION = "1.14"

[context.production.environment]
HUGO_VERSION = "0.89.1"
# Uncomment the next line when moving site to production
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -D -b $DEPLOY_URL"



[[headers]]
for = "/*"

  [headers.values]
  Content-Security-Policy = "upgrade-insecure-requests"
  Strict-Transport-Security = "max-age=31536000;includeSubDomains;preload"
  X-Xss-Protection = "1; mode=block"
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"